### ISSUE TITLE
Sweep: Adding send coin ability to parameters of cli

### ISSUE THREAD

**Issue by onuratakan** [Naruno/Naruno#1737]
### Details

In the cli menu (naruno/cli/main.py) we have a sc (senc coin) option and its get the password, recipient and amount and after its send function that imported before. I want to make same thing for parameter for using without starting menu.

You should add --password --recipient --amount --sendcoin arguments to cli in the arguments function after when the --sendcoin argument is used combine the password recipient and amount in the send funciton.

**Comment by onuratakan** [comment]
sweep:

**Comment by wwzeng1** [comment]
Sweep: retry
